### ISSUE TITLE
k8s rdma 和 ceph ib 网络整合的问题

### ISSUE THREAD

**Issue by JinsYin** [hustcat/k8s-rdma-device-plugin#12]
@carmark 
老师您好，刚刚在小象上看了您的直播，刚好在社区上找到了您，想请教几个关于 k8s rdma 整合 ceph ib 网络的问题。

我现在已知的几个知识（如果理解有误欢迎指出）：

1. 需要一个 rdma device plugin 将 ib 网卡映射到容器（跟 nvidia device plugin 原理一样）
2. 如果使用容器网络，docker 只能映射一个网卡（要么 ib 要么以太），所以只能使用 `hostNetwork`
3. 如果想要使用 RDMA 的话，K8S Node Network 和 Ceph Public Network 都必须有/是 IB 网络（不考虑其他的 RDMA/RoCE 的话）

如果上述都成立，会存在几个问题（如果理解有误欢迎指出）：

1. K8S Pod 如果使用容器网络不就不能访问 Ceph 了吗？（因为 Ceph 的 Public Network 是 IB 网络，而容器网络时以太网）
2. Ceph 官方建议 Public Network 和 Cluster Network 分离，如果 Public Network 使用 IB 网络，Cluster Network 怎么选择呢？再来一个 IB 网络？

> 注：我最理想的情况是 k8s 既能通过 RDMA/IB 访问 Ceph，也能通过以太网访问 Ceph

**Comment by carmark** [comment]
Hi @JinsYin 

You can use IPoIB network if you enable `hostNetwork`.

For second question, you can use another IB network. However it will be enough to use same network if your IB network is 56Gb/s or high throughput.

Thanks

**Comment by JinsYin** [comment]
@carmark Thanks. I got it.
